import { IParkingProvider, ParkingLocation, ParkingGeoJSON, ParkingFacility, ParkingType } from '../types';

/**
 * Calculate distance between two coordinates using Haversine formula
 */
function calculateDistance(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371;
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLon = (lon2 - lon1) * Math.PI / 180;
  const a = Math.sin(dLat / 2) ** 2 + 
            Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * 
            Math.sin(dLon / 2) ** 2;
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
}

/**
 * Demo Parking Provider
 * Provides realistic demo parking locations for testing
 * 
 * Future integration points:
 * - Truck Parking Europe API
 * - TAPA certified parking
 * - OEM parking feeds
 */
export class DemoParkingProvider implements IParkingProvider {
  // Major truck stops and rest areas across Europe
  private readonly demoLocations: Omit<ParkingLocation, 'distanceKm'>[] = [
    // Germany
    {
      id: 'de-truck-1',
      name: 'Autohof Geiselwind',
      address: 'A3 Ausfahrt 76',
      city: 'Geiselwind',
      country: 'Duitsland',
      countryCode: 'DE',
      latitude: 49.7667,
      longitude: 10.4667,
      type: 'truck',
      capacityTotal: 250,
      capacityTruck: 200,
      isFree: false,
      pricePerNight: 15,
      currency: 'EUR',
      isSecured: true,
      isGuarded: true,
      hasCameras: true,
      hasLighting: true,
      safetyRating: 5,
      facilities: ['wc', 'shower', 'restaurant', 'shop', 'wifi', 'security', 'fuel'],
      isOpen24h: true,
      source: 'demo',
      lastUpdated: '2024-01-01',
    },
    {
      id: 'de-truck-2',
      name: 'Rasthof Rhynern Nord',
      address: 'A2 bei Hamm',
      city: 'Hamm',
      country: 'Duitsland',
      countryCode: 'DE',
      latitude: 51.6333,
      longitude: 7.9167,
      type: 'truck',
      capacityTotal: 180,
      capacityTruck: 150,
      isFree: false,
      pricePerNight: 12,
      currency: 'EUR',
      isSecured: true,
      isGuarded: false,
      hasCameras: true,
      hasLighting: true,
      safetyRating: 4,
      facilities: ['wc', 'shower', 'restaurant', 'fuel'],
      isOpen24h: true,
      source: 'demo',
      lastUpdated: '2024-01-01',
    },
    {
      id: 'de-rest-1',
      name: 'Rastplatz Taunusblick',
      address: 'A5 bei Frankfurt',
      city: 'Frankfurt',
      country: 'Duitsland',
      countryCode: 'DE',
      latitude: 50.1667,
      longitude: 8.6333,
      type: 'mixed',
      capacityTotal: 80,
      capacityTruck: 40,
      capacityCar: 40,
      isFree: true,
      isSecured: false,
      isGuarded: false,
      hasCameras: false,
      hasLighting: true,
      safetyRating: 2,
      facilities: ['wc', 'rest_area'],
      isOpen24h: true,
      source: 'demo',
      lastUpdated: '2024-01-01',
    },
    // Netherlands
    {
      id: 'nl-truck-1',
      name: 'Truckparking Maasvlakte',
      address: 'Europaweg 200',
      city: 'Rotterdam',
      country: 'Nederland',
      countryCode: 'NL',
      latitude: 51.9500,
      longitude: 4.0333,
      type: 'truck',
      capacityTotal: 400,
      capacityTruck: 400,
      isFree: false,
      pricePerNight: 18,
      currency: 'EUR',
      isSecured: true,
      isGuarded: true,
      hasCameras: true,
      hasLighting: true,
      safetyRating: 5,
      facilities: ['wc', 'shower', 'restaurant', 'shop', 'wifi', 'security', 'camera'],
      isOpen24h: true,
      source: 'demo',
      lastUpdated: '2024-01-01',
    },
    {
      id: 'nl-truck-2',
      name: 'TruckPark Venlo',
      address: 'A67 afrit Venlo',
      city: 'Venlo',
      country: 'Nederland',
      countryCode: 'NL',
      latitude: 51.3667,
      longitude: 6.1667,
      type: 'truck',
      capacityTotal: 120,
      capacityTruck: 100,
      isFree: false,
      pricePerNight: 14,
      currency: 'EUR',
      isSecured: true,
      isGuarded: false,
      hasCameras: true,
      hasLighting: true,
      safetyRating: 4,
      facilities: ['wc', 'shower', 'wifi', 'camera'],
      isOpen24h: true,
      source: 'demo',
      lastUpdated: '2024-01-01',
    },
    // Belgium
    {
      id: 'be-truck-1',
      name: 'Truckstop Antwerpen',
      address: 'Haven Antwerpen',
      city: 'Antwerpen',
      country: 'België',
      countryCode: 'BE',
      latitude: 51.2667,
      longitude: 4.3333,
      type: 'truck',
      capacityTotal: 200,
      capacityTruck: 180,
      isFree: false,
      pricePerNight: 16,
      currency: 'EUR',
      isSecured: true,
      isGuarded: true,
      hasCameras: true,
      hasLighting: true,
      safetyRating: 5,
      facilities: ['wc', 'shower', 'restaurant', 'shop', 'wifi', 'security'],
      isOpen24h: true,
      source: 'demo',
      lastUpdated: '2024-01-01',
    },
    // France
    {
      id: 'fr-truck-1',
      name: 'Aire de Châlons-en-Champagne',
      address: 'A4 Aire de service',
      city: 'Châlons-en-Champagne',
      country: 'Frankrijk',
      countryCode: 'FR',
      latitude: 48.9500,
      longitude: 4.3667,
      type: 'truck',
      capacityTotal: 150,
      capacityTruck: 120,
      isFree: false,
      pricePerNight: 20,
      currency: 'EUR',
      isSecured: true,
      isGuarded: false,
      hasCameras: true,
      hasLighting: true,
      safetyRating: 4,
      facilities: ['wc', 'shower', 'restaurant', 'fuel'],
      isOpen24h: true,
      source: 'demo',
      lastUpdated: '2024-01-01',
    },
    {
      id: 'fr-rest-1',
      name: 'Aire de Beaune-Tailly',
      address: 'A6 Aire de repos',
      city: 'Beaune',
      country: 'Frankrijk',
      countryCode: 'FR',
      latitude: 47.0167,
      longitude: 4.8500,
      type: 'mixed',
      capacityTotal: 100,
      capacityTruck: 60,
      capacityCar: 40,
      isFree: true,
      isSecured: false,
      isGuarded: false,
      hasCameras: false,
      hasLighting: true,
      safetyRating: 2,
      facilities: ['wc', 'rest_area'],
      isOpen24h: true,
      source: 'demo',
      lastUpdated: '2024-01-01',
    },
    // Austria
    {
      id: 'at-truck-1',
      name: 'Autohof Salzburg',
      address: 'A1 Salzburg West',
      city: 'Salzburg',
      country: 'Oostenrijk',
      countryCode: 'AT',
      latitude: 47.8000,
      longitude: 13.0000,
      type: 'truck',
      capacityTotal: 100,
      capacityTruck: 80,
      isFree: false,
      pricePerNight: 15,
      currency: 'EUR',
      isSecured: true,
      isGuarded: false,
      hasCameras: true,
      hasLighting: true,
      safetyRating: 4,
      facilities: ['wc', 'shower', 'restaurant', 'fuel'],
      isOpen24h: true,
      source: 'demo',
      lastUpdated: '2024-01-01',
    },
    // Italy
    {
      id: 'it-truck-1',
      name: 'Autogrill Modena Nord',
      address: 'A1 Area di Servizio',
      city: 'Modena',
      country: 'Italië',
      countryCode: 'IT',
      latitude: 44.6500,
      longitude: 10.9333,
      type: 'truck',
      capacityTotal: 120,
      capacityTruck: 90,
      isFree: false,
      pricePerNight: 18,
      currency: 'EUR',
      isSecured: true,
      isGuarded: false,
      hasCameras: true,
      hasLighting: true,
      safetyRating: 4,
      facilities: ['wc', 'shower', 'restaurant', 'shop', 'fuel'],
      isOpen24h: true,
      source: 'demo',
      lastUpdated: '2024-01-01',
    },
    {
      id: 'it-truck-2',
      name: 'Brennero Truck Park',
      address: 'A22 Brennero',
      city: 'Brennero',
      country: 'Italië',
      countryCode: 'IT',
      latitude: 47.0000,
      longitude: 11.5000,
      type: 'truck',
      capacityTotal: 80,
      capacityTruck: 70,
      isFree: false,
      pricePerNight: 22,
      currency: 'EUR',
      isSecured: true,
      isGuarded: true,
      hasCameras: true,
      hasLighting: true,
      safetyRating: 5,
      facilities: ['wc', 'shower', 'restaurant', 'wifi', 'security'],
      isOpen24h: true,
      source: 'demo',
      lastUpdated: '2024-01-01',
    },
  ];

  async getLocations(lat: number, lng: number, radiusKm: number): Promise<ParkingLocation[]> {
    // Filter by radius and add distance
    return this.demoLocations
      .map(loc => ({
        ...loc,
        distanceKm: calculateDistance(lat, lng, loc.latitude, loc.longitude),
      }))
      .filter(loc => loc.distanceKm <= radiusKm)
      .sort((a, b) => a.distanceKm! - b.distanceKm!);
  }

  async getGeoJSON(lat: number, lng: number, radiusKm: number): Promise<ParkingGeoJSON> {
    const locations = await this.getLocations(lat, lng, radiusKm);
    
    return {
      type: 'FeatureCollection',
      features: locations.map(loc => ({
        type: 'Feature' as const,
        id: loc.id,
        properties: {
          id: loc.id,
          name: loc.name,
          type: loc.type,
          isFree: loc.isFree,
          isSecured: loc.isSecured,
          capacityTotal: loc.capacityTotal,
          facilities: loc.facilities,
        },
        geometry: {
          type: 'Point' as const,
          coordinates: [loc.longitude, loc.latitude],
        },
      })),
    };
  }
}
